name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go version

      - name: Unittest
        run: |
          make test GO=go

  integ-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go version

      - name: Integration test
        run: |
          make integ-test GO=go

      - name: Helm output diff
        run: |
          make helm-template-diff
