name: CI

on:
  push:
    branches:
      - main

jobs:
  ingress-nginx:
    runs-on: ubuntu-latest
    name: Do snapshot ingress-nginx and create PR if snapshot changed
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Snapshot
        uses: jlandowner/helm-chartsnap-action@v1
        id: helm-chartsnap-action
        with:
          chart:  ingress-nginx
          repo:   https://kubernetes.github.io/ingress-nginx
          values: example/remote/ingress-nginx.values.yaml
          additional_args: "--namespace ingress-nginx --skip-tests"
          update_snapshot: true

  cilium:
    runs-on: ubuntu-latest
    name: Do snapshot cilium and create PR if snapshot changed
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Snapshot
        uses: jlandowner/helm-chartsnap-action@v1
        id: helm-chartsnap-action
        with:
          chart:  cilium
          repo:   https://helm.cilium.io
          values: example/remote/cilium.values.yaml
          additional_args: "--namespace kube-system"
          update_snapshot: true

  nginx-gateway-fabric:
    runs-on: ubuntu-latest
    name: Do snapshot nginx-gateway-fabric and create PR if snapshot changed
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Snapshot
        uses: jlandowner/helm-chartsnap-action@v1
        id: helm-chartsnap-action
        with:
          chart:  oci://ghcr.io/nginxinc/charts/nginx-gateway-fabric
          values: example/remote/nginx-gateway-fabric.values.yaml
          additional_args: "--namespace nginx-gateway"
          update_snapshot: true

  local:
    runs-on: ubuntu-latest
    name: Do snapshot cilium and create PR if snapshot changed
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Snapshot
        uses: jlandowner/helm-chartsnap-action@v1
        id: helm-chartsnap-action
        with:
          chart:  example/app1
          values: example/app1/test/
        continue-on-error: true

      - name: OK if snapshot is changed
        if: steps.helm-chartsnap-action.outcome == 'failure'
        shell: bash
        run: |
          echo "snapshot changed"

      - name: Fail if snapshot is not changed
        if: steps.helm-chartsnap-action.outcome == 'success'
        shell: bash
        run: |
          echo "snapshot not changed"; exit 1