name: Release build
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: 'Git tag to create'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Create tag
        run: |
          git tag ${GIT_TAG}
          git push origin ${GIT_TAG}
        env:
          GIT_TAG: ${{ github.event.inputs.tag }}

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
